### ISSUE TITLE
Allow for recursive file patterns

### ISSUE THREAD

**Issue by dreimerPDX** [nimble-code/Cobra#12]
On a repository with a nested file structure, common with java projects, there is no easy way to specify running Cobra across these files. 

I suggest having the ability to run cobra like `cobra --recursive "*.java"` option or the ability to use recursive file globing such as `**/*.java`

**Comment by nimble-code** [comment]
good point -- I usually first collect all filenames I'm interested in in a single file at the root of the directory, and then pass that to cobra to run the checks. something like:
$ du -a . | grep -e "\.[ch]$" > c_files
$ cobra `cat c_files`
that gives me the control I need, also to omit files I don't want to scan, by omitting them from the file

**Comment by pigsinablanket** [comment]
I tried this approach before but was running into issues with some larger projects, `bash: /home/dan/git/Cobra/bin_linux/cobra: Argument list too long`

**Comment by nimble-code** [comment]
doesn't seem to happen on my system (windows 10 + cygwin, or with WSL linux)
would an option to process one file at a time from a list be a solution?  something like --sequential file
(or some better term)

**Comment by pigsinablanket** [comment]
It only happens with larger monorepos (such as https://github.com/apache/camel running `cobra -json -pe "@ident ( String p:@ident ) { .* ( :p . equals ( @str ) )" $(cat files)`) as Bash has a 2mb argument size limit. 

A `--sequential file` would involve an unnecessary write to file and the workflow would have to involve
```
find . -type f -name '*.java' > files
cobra --sequential files
```
when a more streamlined approach is to have cobra support one of the abilities I mentioned above so that only cobra would need to be called. 

I'd understand if you are apprehensive to add such functionality to cobra and having `--sequential file` is a workable solution

**Comment by nimble-code** [comment]
let me give that some thought

**Comment by nimble-code** [comment]
Updated the sources to support this. There are two new commandline options.
The first is
  $ cobra -F file
which gets cobra to read the list of files to process from file 'file' instead of from the command-line.
This gives a little more control than a default 'find' since it allows you to edit the list (e.g., to remove test files).
The second option is:
  $ cobra -recursive 'pattern'
e.g.
  $ cobra -recursive '*.java'
or
 $ cobra -recursive '*.[ch]'
as suggested. This runs 'find' in the background (which is assumed to be installed) and generates the files in a temporary file that is then processed just like it would with the -F option.
Hopefully that solves the issue for large code archives.

**Comment by nimble-code** [comment]
(note: cobra uses single hyphen commands.  double hyphens get passed to a back-end, if defined, or ignored....
