### ISSUE TITLE
Support the JUnit XML format for Cobra output

### ISSUE THREAD

**Issue by mjeronimo** [nimble-code/Cobra#19]
In order to integrate with the Jenkins CI/CD tool, it would be helpful to have Cobra output detected issues in the [JUnit XML format](https://llg.cubic.org/docs/junit/), which is understood by Jenkins.

**Comment by nimble-code** [comment]
will look into it

**Comment by nimble-code** [comment]
the current plan is to support JSON output format, and possibly add converters to carry that file-format into (or from) JUnit and SARIF etc.
this is part of the broader current effort to allow Cobra to both write and also to read JSON format to pre-define named pattern sets that can then be used in further analyses.
rationale: there's a large number of possible output formats available that can facilitate integration with different platforms and frameworks -- rather than supporting all those formats, it is better to support a single one, that contains all necessary information, and allow conversions from that one format into the others -- a set that can then be maintained and extended or adapted independently of the main cobra analysis engine.

**Comment by sthagen** [comment]
I am happy to support that. In practice it is frustrating as user to wait hours for an analysis to finish and then have the process die while trying hard to produce the junit format xml file. As a user, I expect the analyzer to use streaming (small scope transactions) and only keep the minimum reporting aggregates in memory. Thus, do what it can best: Analyze, and expose transformable snippets as it proceeds and maybe in ending a minimal aggregate report. Converters (off-prcess) can take it from there. As a member of the [OASIS SARIF TC](https://github.com/oasis-tcs/sarif-spec/) I would be happy to support providing a to SARIF converter from the JSON snippets you come up with, @nimble-code

**Comment by nimble-code** [comment]
I've implemented a prototype of the converter from Cobra's JSON output format into JUnit format, but I hope you can look at the initial version to see if it populates the fields in the best way.  I'm attaching a sample of how it appears now, but do let me know if you thing a different field assignment is better -- if you have an example, I can easily change it. Here's what I currently generate:
<testsuites>
<testsuite name="cwe_457">
 <properties>
  <property name="cobra" value="warning">
 </properties>
 <testcase name="match">
 <failure message="uninitialized var b?">
 file=cobra_lib.c line=1693
 </failure>
 </testcase>
</testsuite>
<testsuite name="cwe_197b">
 <properties>
  <property name="cobra" value="warning">
 </properties>
 <testcase name="match">
 <failure message="potential loss of information in cast of n">
 file=cobra_prog.c line=3083
 </failure>
 </testcase>
 <testcase name="match">
 <failure message="potential loss of information in cast of n">
 file=cobra_prog.c line=3074
 </failure>
 </testcase>

**Comment by nimble-code** [comment]
[junit.txt](https://github.com/nimble-code/Cobra/files/7908023/junit.txt)
