### ISSUE TITLE
False positive: "Fct names also used as variables"

### ISSUE THREAD

**Issue by mjeronimo** [nimble-code/Cobra#23]
Using the Basic rule set, when a function name is provided to a macro, the rule incorrectly identifies this as using the function name as a variable. I've noticed that this is only for the first occurrence in the function (the second macro invocation does not provoke the warning). 

To reproduce:

`$ cobra -C++ -comments -f basic t1.c
`

Where t1.c is:

```
rcl_ret_t
rcl_client_init(
  rcl_client_t * client,
  const rcl_node_t * node,
  const rosidl_service_type_support_t * type_support,
  const char * service_name,
  const rcl_client_options_t * options)
{
  TRACEPOINT(
    rcl_client_init,
    (const void *)client,
    (const void *)node,
    (const void *)client->impl->rmw_handle,
    remapped_service_name);

  ANOTHER_MACRO(
    rcl_client_init,
    (const void *)client,
    (const void *)node,
    (const void *)client->impl->rmw_handle,
    remapped_service_name);

   return 0;
}
```

Results in:

```
=== Fct names also used as variables: 1
t1.c:11:
  1:     11      rcl_client_init,
```

**Comment by nimble-code** [comment]
without preprocessing enabled, Cobra cannot tell that the name appears in a macro call, rather than a function call, so the warning for this case would be difficult to suppress. With preprocessing, the function name should appear as a regular call (we can't tell from the example, because the macro definitions aren't included).  so, we cannot change the checker to prevent this warning. (note that all static analyzer have to make approximations to make the analysis problem computationally decidable -- but hopefully the false positives are easy to recognize)
