### ISSUE TITLE
Improvements requested for the json_convert SARIF output

### ISSUE THREAD

**Issue by mjeronimo** [nimble-code/Cobra#49]
Besides the fixes in this PR: https://github.com/nimble-code/Cobra/pull/48

There are a few items that would make the SARIF output more useful in an IDE:

* The **rules/fullDescription/text** appears to be truncated. For example, text descriptions are strings like "Missing" and "Inconsistent". It seems like some full description string has been truncated to be only the first word.
* According to the standard, the **rules/messageStrings/default/text** item should be a complete sentence ending in a period. It is current a string like, "lines 238..238". This should be a more complete sentence describing the rule. 
* There is no "artifacts" entry

Here is a screen capture from the Visual Studio Code SARIF plug-in that demonstrates the first two items:

![image](https://user-images.githubusercontent.com/865395/162095101-ff6b41fa-4c57-4f3d-ad96-edc7c85fed68.png)

**Comment by Ronoman** [comment]
There are a few more cases where Cobra outputs invalid SARIF (really, invalid JSON) that I have found.

1. If a rule contains a `:` in a `.def` file, this will incorrectly be escaped with a `\` in the resulting SARIF.
    a. Example: [Line 206](https://github.com/nimble-code/Cobra/blob/master/rules/C%2B%2B/autosar.def#L206) in `autosar.def` defines the rule `All code shall conform to ISO/IEC 14882:2014 -Programming Language C++ and shall not use deprecated features.`. If this rule shows up in SARIF output, `14882:2014` becomes `14882\:2014`, which is invalid JSON.
2. If a rule contains a `"` in a `.def` file, this prematurely terminates the rule in the resulting SARIF.
    a. Example: [Line 244](https://github.com/nimble-code/Cobra/blob/master/rules/C%2B%2B/autosar.def#L344) in `autosar.def` defines the rule `All declarations of user-defined types, static and non-static data members, functions and methods shall be preceded by documentation using "///" comments and "@tag" tags.`. If this rule shows up in SARIF output, the resulting text is `"(Required) Declarations of user-defined types, static and non-static data members, functions and methods shall be preceded by documentation using \"`, which is both invalid JSON (escaping the ending quote, without adding another quote to properly terminate the string), and not the full rule text.
    b. See also lines [508](https://github.com/nimble-code/Cobra/blob/master/rules/C%2B%2B/autosar.def#L508), [515](https://github.com/nimble-code/Cobra/blob/master/rules/C%2B%2B/autosar.def#L515), [722](https://github.com/nimble-code/Cobra/blob/master/rules/C%2B%2B/autosar.def#L722), and [2289](https://github.com/nimble-code/Cobra/blob/master/rules/C%2B%2B/autosar.def#L2289) for more rules that likely would be parsed incorrectly.

I suspect that these issues arise from [cleaned_up](https://github.com/nimble-code/Cobra/blob/c1c994ab48e984ed4480efab4cf77448679553ca/src/cobra_json.c#L29) in `cobra_json.c`.

**Comment by nimble-code** [comment]
I've updated cobra_json.c to exclude an escape before the : character in cleaned_up() as suggested,
and I've modified the rulesets C++/autosar.def cwe/cwe_416.def  to make sure there are no " characters in the captions
hopefully this solves both issues!

**Comment by mjeronimo** [comment]
Great, thanks. We could still use some help on the first few items reported in this thread to help improve the experience when using SARIF with the VSCode plugin. I can split these out into separate issues if that would be helpful.

**Comment by nimble-code** [comment]
oops - i missed those -- will be looking into these next

**Comment by mjeronimo** [comment]
The first one might have been fixed already (I may have submitted a PR for that one; I don't recall).

**Comment by Ronoman** [comment]
The [tool.driver.rules](https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10540994) field is (I believe) meant to define the rules that this static analyzer has reported, once. The SARIF spec says that it can be all of the rules that the static analyzer is capable of reporting, though I believe some of the other static analyzers we're using are only reporting rules that they have found for a single run of the tool.

For "lines n..m", I'm assuming that is reporting the location within a file (Artifact as the SARIF spec refers to them) that a rule violation has occurred. If that assumption is correct, this can instead be reported in a Result's locations.physicalLocation.region field, like so:

```
{
  "ruleId": "misra-c2012-4.1",
  "level": "warning",
  "kind": "review",
   "message": {
    "text": " Octal and hexadecimal escape sequences shall be terminated"
  },
  "locations": [
    {
      "physicalLocation": {
        "artifactLocation": {
          "uri": "src/logging.c",
          "index": 47
        },
        "region": {
          "startLine": 791
        }
      }
    }
  ]
}
```

For more information, see [3.29](https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10541116) and [3.30](https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10541123) of the SARIF spec, which contains fields like `startColumn` and endLine.

For the Artifact object, here is an example of what `cppcheck` contains:

```
"artifacts": [
  {
    "location": {
      "uri": "include/rcutils/allocator.h"
    }
  },
  {
    "location": {
      "uri": "include/rcutils/cmdline_parser.h"
    }
  },
  {
    "location": {
      "uri": "include/rcutils/env.h"
    }
  },
...
```

It is a list of locations, which have `uri`'s that are relative paths to files. One of the things we're looking to do is to add a `uriBaseId` field, such that `concatenate(uriBaseId, uri)` is an absolute filepath, instead of the relative seen above (`cppcheck` is not currently conforming to this). Later on in the SARIF file within the Results objects, each Result.physicalLocation.artifactLocation field will refer back to one of these entries. See the first code block for details, but it contains the file uri again, but also an index which is the corresponding index into the `artifacts` array.

Let me know if you have more questions, or if I was unclear about something here (lots of code and text, so I wouldn't be surprised if I forgot something or was vague).

**Comment by nimble-code** [comment]
that's very useful -- thank you!
i'm still a bit struggling though -- right now the results are reports under runs.tool.driver but I understand that this is the wrong place for this, which should be under a different tree rooted in results which starts with a short description and then the results.locations entry.
did I get that right?  so I should ditch the runs.tool.driver part and replace it with results...  (for now, until we add the additioninfo for the runs part)

**Comment by Ronoman** [comment]
`runs.tool.driver.rules` is still an okay place to put a list of the rules that were violated, but it shouldn't refer to any locations within Artifacts (files) that link it to a specific instance of a violation. So I wouldn't fully ditch `runs.tool.driver`, but you are correct that Results (specific instances of rule violations) should be reported in the `runs.results` array.

For your reference, here is a SARIF file output by `cppcheck`: https://gist.github.com/Ronoman/78c8fc8888b7bc5fffb441042cdd1c39. It's a long file (30k+ lines) so I'd recommend pulling it into an editor that can parse JSON nicely. It is reporting rules and results in the format that we'd like them (as far as I'm aware). The one issue I know of with this file is that artifacts don't refer to absolute paths (it only uses the `uri` field and provides only relative paths, which isn't sufficient). I'll look into fixing this for `cppcheck`, but other than that issue it is hopefully a reasonable (albeit long) reference for SARIF output that is mostly conformant to the spec.

**Comment by nimble-code** [comment]
I've updated the source of json_convert.c to reflect the changes.
closer to compliant now -- though I didn't change the location data itself: file-references are still relative.
I'd hesitate to switch to absolute pathnames as well -- the absolute name on my system (or anyone else's system) isn't going to be helpful to others since the package we're analyzing  can be stored in a user-specific location that wouldn't be general.
if i were to add it, it would likely remain an optionflag to use absolute rather than relative pathnames in the output...

**Comment by Ronoman** [comment]
I had a similar discussion with @mjeronimo about relative vs absolute file paths (see the thread [here](https://github.com/space-ros/space-ros/issues/56#issuecomment-1207082081)). Tools that process SARIF (like [Microsoft DevLab's Sarif Viewer](https://marketplace.visualstudio.com/items?itemName=MS-SarifVSCode.sarif-viewer), which we are planning on leveraging) are not capable of finding a file based on a relative file path, unless you're very careful about what that path is relative to.

I think that keeping `uri` relative is a great idea, so that it is system agnostic. However, the SARIF consumer (developer or automated tool) will want to locate the file absolutely eventually. This is what the `uriBaseId` field is for: `uriBaseId + uri` should absolutely locate the file. I think if this is implemented for `json_convert`, the tools/users consuming this data can either refer to `uri` alone, or `uriBaseId + uri` if they want the full path, removing the need for a flag in `json_convert` to specify which is desired.

I'm open to alternatives to this, but in the end having a way to locate a file absolutely with _just_ the information present in the SARIF file is important.

**Comment by nimble-code** [comment]
would an argument to json_convert be usable, if used to set the uriBasId field?
something like:
     json_convert -sarif -baseid=`pwd`  -f json_output.txt
which then populates the uriBaseId field in the sarif output?
(downside may be that it's a single setting that would be used for all locations)

**Comment by nimble-code** [comment]
I've made this update (version 1.2 from today)
usage: json_convert [options] -f filename.json
  -V -- print version number and exit
  -v -- prints the nr of valid records read on standard output
  -junit -- produce output in JUNIT format (default)
  -sarif -- produce output in SARIF format
  -base=pathname -- add a uriBaseId field set to pathname (SARIF format)
   pathname must contain at least one / and no " characters
  -f filename -- read JSON input from filename

**Comment by mjeronimo** [comment]
@Ronoman  Have the items in this issue been address so that we can close this one?

**Comment by nimble-code** [comment]
Yes they have -- there is another update coming though (today) of json_convert to version 1.3 where we're adding an extra option (command-line flag -a) to generate the SARIF output in a more systematic/logical form, with a rules section defining one category for each type of warning in the results section, and using the ruleIndex field to refer to the categories.  This also helps to make the output a little shorter.
