### ISSUE TITLE
Compile issues on arch-6.2.8. | cobra_lib.c:1457:52 err: %s directive output may be truncated

### ISSUE THREAD

**Issue by cubuzz** [nimble-code/Cobra#61]
Compiling on Arch 6.2.8 runs into errors with cc. Full build output below:

```
cc -I. -Wall -O2 -pedantic -Werror -Wshadow -std=c99 -DYY_NO_INPUT   -c -o cobra_lib.o cobra_lib.c
cobra_lib.c: In function ‘load_map’:
cobra_lib.c:1457:52: error: ‘%s’ directive output may be truncated writing up to 1021 bytes into a region of size between 2 and 1023 [-Werror=format-truncation=]
 1457 |                 {       snprintf(a, sizeof(a), "%s/%s", C_BASE, s);
      |                                                    ^~
cobra_lib.c:1457:25: note: ‘snprintf’ output between 2 and 2044 bytes into a destination of size 1024
 1457 |                 {       snprintf(a, sizeof(a), "%s/%s", C_BASE, s);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by nimble-code** [comment]
thanks for reporting -- will look into it

**Comment by nimble-code** [comment]
It's an odd error report, because there's a conditional right before this call to snprintf that checks the lengths and prevents the truncation -- the check is necessary because the lengths of C_BASE and parameter s aren't otherwise bounded.
the gcc manpage notes that the warning can be inaccurate -- to make it work more conservative I can add -Wformat-truncation=1 to the makefile though. I guess I'll do that for V4.4
