### ISSUE TITLE
Infer finds some bugs in Cobra

### ISSUE THREAD

**Issue by TomMD** [nimble-code/Cobra#8]
I ran Muse (i.e. infer, shellcheck) on Cobra, [results here](https://console.muse.dev/result/TomMD/Cobra/01EQBVB7JSY0K01M5PZY91G4QK?tab=results).

The main findings are:

1. `efree` not actually freeing memory - seems intentional, but certainly means there are leaks.
2. Some dead stores - most are uninteresting (int ret=0 ; ... ; ret = some_call(); ... ; return ret).  However one so far does appear more like junk code that is dead due to refactor or perhaps missing logic (here https://github.com/TomMD/Cobra/blob/ce88343992eb7f16c4b67ca108033b037d0f6354/src/cobra_lib.c#L2202).

**Comment by nimble-code** [comment]
The efree not releasing memory is indeed intentional:: it's faster and memory use is negligible anyway. (standard malloc can have quadratic behavior).
Issue 2 is interesting -- the from/upto settings aren't used. Will have to dig a little deeper to see if I meant this as the initial part of a new thing, or if it's obsolete due to a later refactor. Good find!

**Comment by nimble-code** [comment]
most of the non-memory related infer findings are non-actionable alas.  for instance, it complains when you use ++b to return a value that the new value of b isn't used. true, but not too exciting, and writing (b+1) instead of ++b doesn't seem a great improvement, although it would remove the warning....
decided to replace a few of these in the next update, but not all
